services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka_producer:
    build:
      context: .
      dockerfile: kafka_producer/Dockerfile
    container_name: kafka_producer
    depends_on:
      - kafka
    volumes:
      - ./data:/app/data
    command: python3 kafka_producer.py

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
    - "7077:7077"
    - "8080:8080"
    depends_on:
      - kafka

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
    - "8081:8081"

  spark-submit:
    image: bitnami/spark:latest
    container_name: spark-submit
    volumes:
      - ./spark_streaming:/app/spark_streaming
      - ./spark_streaming/checkpoint:/app/spark_streaming/checkpoint
      - ./spark_streaming/output/parquet:/app/spark_streaming/output/parquet
    working_dir: /app/spark_streaming
    command: >
      /bin/bash -c "
      /opt/bitnami/spark/bin/spark-submit \
      --master spark://spark-master:7077 \
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0 \
      --conf spark.jars.ivy=/tmp/.ivy \
      /app/spark_streaming/spark_stream.py
      "
    depends_on:
      - spark-master
      - spark-worker

  sqlite_loader:
    build:
      context: .
      dockerfile: /sqlite_loader/Dockerfile
    container_name: sqlite_loader
    depends_on:
      - spark-submit
      - kafka_producer
    volumes:
      - ./spark_streaming/output:/app/parquet_data
      - ./sqlite_loader/data:/app/sqlite_data
    command: python3 parquet_to_sqlite.py